############################
# RPM-specific Makefile	   #
# http://yum.postgresql.org    #
#                          #
# Devrim Gunduz            #
# devrim@gunduz.org        #
############################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.rhel6
SPECFILE="slony1-II.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
