############################
# RPM-specific Makefile	   #
# http://yum.postgresql.org    #
#                          #
# Devrim Gunduz            #
# devrim@gunduz.org        #
############################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.rhel5
SPECFILE="postgresql-9.0.spec"
HOMEDIR=$HOMEDIR

# Now, include global Makefile
include ../../../common/Makefile.global
