############################
# RPM-specific Makefile	   #
# http://yum.postgresql.org    #
#                          #
# Devrim Gunduz            #
# devrim@gunduz.org        #
############################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.f18
SPECFILE="proj.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
